services:
  api:
    build:
      context: ./UrlShortener.Api
    container_name: urlshortener-api
    ports:
      - "5001:8080"
    environment:
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=urlshortener;Username=postgres;Password=postgres
      Redis__ConnectionString: redis:6379
      Redis__ShortUrlTtlSeconds: 3600
      RateLimit__PermitLimit: 10
      RateLimit__WindowSeconds: 60
      ASPNETCORE_URLS: http://0.0.0.0:8080
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: urlshortener-postgres
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: urlshortener-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
